#!/bin/bash

# smoker_mobile_app version bumper
# Usage: ./scripts/bump_version.sh [major|minor|patch|build|1|2|3|4]

PUBSPEC="pubspec.yaml"

if [ ! -f "$PUBSPEC" ]; then
    echo "Error: pubspec.yaml not found in current directory."
    exit 1
fi

# Get current version line
VERSION_LINE=$(grep "^version: " "$PUBSPEC")
VERSION_VALUE=$(echo "$VERSION_LINE" | sed -e 's/^version: *//')

if [[ "$VERSION_VALUE" == *"+"* ]]; then
    VERSION_PART=$(echo "$VERSION_VALUE" | cut -d'+' -f1)
    BUILD_PART=$(echo "$VERSION_VALUE" | cut -d'+' -f2)
else
    VERSION_PART="$VERSION_VALUE"
    BUILD_PART="0"
fi

# Split version into components
IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_PART"

# Calculate potential versions
PROP_BUILD="$MAJOR.$MINOR.$PATCH+$((BUILD_PART + 1))"
PROP_PATCH="$MAJOR.$MINOR.$((PATCH + 1))+$((BUILD_PART + 1))"
PROP_MINOR="$MAJOR.$((MINOR + 1)).0+$((BUILD_PART + 1))"
PROP_MAJOR="$((MAJOR + 1)).0.0+$((BUILD_PART + 1))"

BUMP_TYPE=$1
CHOICE=""

if [ -z "$BUMP_TYPE" ]; then
    if [ -t 0 ]; then
        # Interactive prompt
        echo "Current version: $VERSION_PART+$BUILD_PART"
        echo ""
        echo "Select version bump option:"
        echo "  1) Build  -> $PROP_BUILD (Proposed Default)"
        echo "  2) Patch  -> $PROP_PATCH"
        echo "  3) Minor  -> $PROP_MINOR"
        echo "  4) Major  -> $PROP_MAJOR"
        echo ""
        read -p "Enter choice [1-4] (blank to accept proposed): " CHOICE
        if [ -z "$CHOICE" ]; then
            CHOICE="1"
        fi
    else
        # Non-interactive fallback
        CHOICE="1"
    fi
else
    # Map command line arguments
    case $BUMP_TYPE in
        major|4) CHOICE="4" ;;
        minor|3) CHOICE="3" ;;
        patch|2) CHOICE="2" ;;
        build|1) CHOICE="1" ;;
        *)
            echo "Usage: $0 [major|minor|patch|build|1|2|3|4]"
            exit 1
            ;;
    esac
fi

case $CHOICE in
    1)
        NEW_VERSION="$PROP_BUILD"
        BUMP_NAME="Build"
        ;;
    2)
        NEW_VERSION="$PROP_PATCH"
        BUMP_NAME="Patch"
        ;;
    3)
        NEW_VERSION="$PROP_MINOR"
        BUMP_NAME="Minor"
        ;;
    4)
        NEW_VERSION="$PROP_MAJOR"
        BUMP_NAME="Major"
        ;;
    *)
        echo "Invalid choice: $CHOICE"
        exit 1
        ;;
esac

echo "Bumping version ($BUMP_NAME) from $VERSION_PART+$BUILD_PART to $NEW_VERSION"

# Use sed to replace the version line
sed -i "s/^version: .*/version: $NEW_VERSION/" "$PUBSPEC"

echo "Updated $PUBSPEC successfully."

# Update version.dart constant for hot reloading support
VERSION_FILE="lib/core/constants/version.dart"
mkdir -p "$(dirname "$VERSION_FILE")"
echo "// Generated by bump_version.sh. Do not edit manually." > "$VERSION_FILE"
echo "const String appVersion = '$NEW_VERSION';" >> "$VERSION_FILE"
echo "Updated $VERSION_FILE successfully."


